---
version: '3'

services:
  pdrdb:
    container_name: pdrdb
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/pdrdb:latest
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - pdrdb
